FROM python:3.9

WORKDIR /app

COPY . ./

RUN pip install -r /app/Docker/requirments.txt

CMD echo "Hello from planify"

LABEL maintainer='Mohamed Hassan'
LABEL description='Graduation project, Residential Floor Plan Generation\
Using Deep Learning Techniques [specially room size estimation with Graph Neural Networks].'


